"""Changed the datatype of text1 to JSON

Revision ID: 522e845f3e40
Revises: e492a7b8d07d
Create Date: 2023-04-05 16:51:13.861769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522e845f3e40'
down_revision = 'e492a7b8d07d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('texts', schema=None) as batch_op:
        batch_op.alter_column('text1',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('texts', schema=None) as batch_op:
        batch_op.alter_column('text1',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
