"""Changed the datatype of text1 to JSON

Revision ID: 958e05aba4e5
Revises: 522e845f3e40
Create Date: 2023-04-05 17:09:12.695183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '958e05aba4e5'
down_revision = '522e845f3e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_transcriptions', schema=None) as batch_op:
        batch_op.alter_column('text1',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('texts', schema=None) as batch_op:
        batch_op.drop_column('tran3')
        batch_op.drop_column('text2')
        batch_op.drop_column('text6')
        batch_op.drop_column('text4')
        batch_op.drop_column('text1')
        batch_op.drop_column('text3')
        batch_op.drop_column('tran5')
        batch_op.drop_column('text7')
        batch_op.drop_column('text5')
        batch_op.drop_column('tran4')
        batch_op.drop_column('tran7')
        batch_op.drop_column('tran1')
        batch_op.drop_column('tran2')
        batch_op.drop_column('tran6')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('texts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tran6', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('tran2', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('tran1', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('tran7', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('tran4', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('text5', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('text7', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('tran5', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('text3', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('text1', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('text4', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('text6', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('text2', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('tran3', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('text_transcriptions', schema=None) as batch_op:
        batch_op.alter_column('text1',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
