"""Added dialect column

Revision ID: a6bb0b68ad4c
Revises: f9e5796fc2e7
Create Date: 2023-04-19 14:34:50.629479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6bb0b68ad4c'
down_revision = 'f9e5796fc2e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_transcriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dialect', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_transcriptions', schema=None) as batch_op:
        batch_op.drop_column('dialect')

    # ### end Alembic commands ###
