"""Changed the datatype of TextTranscription to JSON

Revision ID: c10a45c80c1b
Revises: 958e05aba4e5
Create Date: 2023-04-05 17:13:19.631406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10a45c80c1b'
down_revision = '958e05aba4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_transcriptions', schema=None) as batch_op:
        batch_op.alter_column('tr1',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('text2',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('tr2',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('text3',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('tr3',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('text4',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('tr4',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('text5',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('tr5',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('text6',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('tr6',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('text7',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('tr7',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_transcriptions', schema=None) as batch_op:
        batch_op.alter_column('tr7',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('text7',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('tr6',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('text6',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('tr5',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('text5',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('tr4',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('text4',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('tr3',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('text3',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('tr2',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('text2',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('tr1',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
