"""created text_transcription table

Revision ID: e492a7b8d07d
Revises: a8e7a2bfc9c4
Create Date: 2023-04-05 15:20:58.974609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e492a7b8d07d'
down_revision = 'a8e7a2bfc9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_transcriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('text1', sa.String(), nullable=True),
    sa.Column('tr1', sa.String(), nullable=True),
    sa.Column('text2', sa.String(), nullable=True),
    sa.Column('tr2', sa.String(), nullable=True),
    sa.Column('text3', sa.String(), nullable=True),
    sa.Column('tr3', sa.String(), nullable=True),
    sa.Column('text4', sa.String(), nullable=True),
    sa.Column('tr4', sa.String(), nullable=True),
    sa.Column('text5', sa.String(), nullable=True),
    sa.Column('tr5', sa.String(), nullable=True),
    sa.Column('text6', sa.String(), nullable=True),
    sa.Column('tr6', sa.String(), nullable=True),
    sa.Column('text7', sa.String(), nullable=True),
    sa.Column('tr7', sa.String(), nullable=True),
    sa.Column('text_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], name=op.f('fk_text_transcriptions_text_id_texts')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('texts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tran1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('text2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tran2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('text3', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tran3', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('text4', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tran4', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('text5', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tran5', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('text6', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tran6', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('text7', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tran7', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('texts', schema=None) as batch_op:
        batch_op.drop_column('tran7')
        batch_op.drop_column('text7')
        batch_op.drop_column('tran6')
        batch_op.drop_column('text6')
        batch_op.drop_column('tran5')
        batch_op.drop_column('text5')
        batch_op.drop_column('tran4')
        batch_op.drop_column('text4')
        batch_op.drop_column('tran3')
        batch_op.drop_column('text3')
        batch_op.drop_column('tran2')
        batch_op.drop_column('text2')
        batch_op.drop_column('tran1')
        batch_op.drop_column('text1')

    op.drop_table('text_transcriptions')
    # ### end Alembic commands ###
